name = "focus-reader-db-migrations"
compatibility_date = "2026-02-13"

[[d1_databases]]
binding = "FOCUS_DB"
database_name = "focus-reader-db"
database_id = "b4a813e6-ea46-4e4a-8985-512073565630"
migrations_dir = "migrations"
