name = "focus-reader-db-migrations"
compatibility_date = "2026-02-13"

[[d1_databases]]
binding = "FOCUS_DB"
database_name = "focus-reader-db"
database_id = "6df49da0-c4e0-4f1e-b2bf-7658b61caf75"
migrations_dir = "migrations"
